# Generated by Django 2.1.12 on 2019-09-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('service_area', models.CharField(max_length=100)),
                ('local_address', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=120, null=True)),
                ('pin', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='register_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Required', max_length=250)),
                ('email', models.EmailField(help_text='Required', max_length=250)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('Confirm_password', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userreg.register_model'),
        ),
    ]
